# workflow
# Should have Name
name: Hello
# on tell when workflow run
on: 
  workflow_dispatch: 
# Jobs
# Should be inside the workflow
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello everyone
        run: echo "Hello Friends"

# Steps
# Should be inside the job

# Actions
# Should be inside the steps 
