# python code change then lint run
name: Auto Linte

on: 
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Install Linter
        run: pip install ruff
        
        
